# Generated by Django 3.1.8 on 2024-05-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employe_id',
            new_name='employee_id',
        ),
    ]
