# Generated by Django 3.1.8 on 2024-05-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_types',
            field=models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR'), ('developer', 'Developer')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
